### ISSUE TITLE
想要工资有些提升

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/gitblog#155]
昨天面了一个人。技术不如我但工资比我高好多。

**Comment by gy0857478** [comment]
QQ

**Comment by yihong0618** [comment]
> QQ

惨。。。

**Comment by yihong0618** [comment]
看起来是要换工作了。

**Comment by yihong0618** [comment]
一年过去了。
明年初开始尝试换工作。
也在这儿呆够了。

需要提升下自己。在很多方面。

**Comment by gy0857478** [comment]
今年也剛換工作 加油!

**Comment by yihong0618** [comment]
> 今年也剛換工作 加油！

嗯啊，谢谢。

**Comment by yihong0618** [comment]
大概的计划：

- [ ] 刷一点点算法
- [ ] 在网上打开自己的简历
- [ ] 把网络知识多学一下
- [ ] 英语口语练一下
- [ ] 今年 11 月开始尝试打开简历，没有猎头找的话投 1-2 个
- [ ] 明年年初开始正式找一下
- [ ] 除非有变化，否则接下来按这节奏走

**Comment by gy0857478** [comment]
學算法可以看看這個

https://github.com/chefyuan/algorithm-base

**Comment by yihong0618** [comment]
今天被气到了。。。
也太他妈菜了，告诉还不听。。。

**Comment by JsonViewerMusk** [comment]
那个人是武汉的 
我觉得工资差异体现在地区水平的差异应该也是有的
我觉得没必要受到打击
你来到一线城市的话起步20k也不是难事

**Comment by a8b7** [comment]
> > 大连还好吧。混个12 应该不难， 沈阳更坑 https://docs.qq.com/sheet/DV3piSGFDYXhkcERL?tab=BB08J2&_t=1619163550158
> 
> 卧槽。

我看的都不想找工作

**Comment by nshen** [comment]
> > > 大连还好吧。混个12 应该不难， 沈阳更坑 https://docs.qq.com/sheet/DV3piSGFDYXhkcERL?tab=BB08J2&_t=1619163550158
> > 
> > 
> > 卧槽。
> 
> 我看的都不想找工作

感觉沈阳就是，大公司都劣币驱逐良币，小公司就是拖欠工资。

上面还有我所在的公司，哈哈。
