### ISSUE TITLE
更自动的触发action

### ISSUE THREAD

**Issue by HuJJ-NB** [yihong0618/gitblog#236]
我对您的仓库做了以下更改

```python
.git/workflows/generate_readme.yml
      issues:
---     types: [opened, edited]
+++     types: [opened, edited, closed, reopened, labeled, unlabeled]
      issue_comment:
---     types: [created, edited]
+++     types: [created, edited, deleted]
```

以期望实现更自动的操作。

但是对于友情链接，打心的行为我没能找到可以触发的事件，看您的做法应该是取消勾选和和勾选复选框来更新内容，实现触发。

我期望有一个更直观的操作方式，也许可以用作者`Quate reply`并标注的方式来实现对某个友情链接的认可。

**Comment by HuJJ-NB** [comment]
另外我发现我的issues也会触发action,并且显示在主页，能不能加一个功能对作者做一个区分，另外，tokens、用户名、邮箱等等，也许可以提出来一个`config.json`统一管理。

**Comment by yihong0618** [comment]
其它挺好的
友情链接我是不想自动化的，因为需要自己看一下。

**Comment by HuJJ-NB** [comment]
本来的想法是，打心之后自动完成下面的操作，也不是完全自动还是要审批一下的。想了想，貌似也不太能实现，而且无伤大雅。

另外，我觉得你生成的README格式有点不太标准。比如你大标题下面的说明和rss应该是两行的，GitHub渲染出来显示的是一行，感觉是因为GitHub的readme的渲染和issue的渲染不一样，readme里面这个中间没空行的正文段会识别成同一段。

所以，我把你的仓库clone到了本地，在vs code里用markdown的插件对照着整理了一下。

最后是action里面，我上面的issue说的也不太对，其实issue的open和博客没关系，因为是根据标签显示的，所以对issue来说labeled、unlabeled、close、reopen、deleted，这几个才会影响博客的显示。

还有一个是action里的git config的时候，用户名设置用的是邮箱的环境变量。

我打算先改，然后整理一下commit，给你提个pr，这样你可以选择接受哪些修改，因为可能我认为不太符合我的直觉然后修改的部分，你认为不需要改或者不能改。

**Comment by yihong0618** [comment]
没问题，always welcome thanks.

**Comment by yihong0618** [comment]
先关了哈～有问题重新 open
