### ISSUE TITLE
博主你好！我给你写了邮件，担心你收不到，所以在此给你留言。

### ISSUE THREAD

**Issue by shyn** [yihong0618/gitblog#276]
博主你好！我给你写了邮件，担心你收不到，所以在此给你留言。

按你的指导，我也开始用 GitHub Issues 写博客。但是当我「需要再次对博客进行编辑时」感觉体验很不好。
Github Issues 自带的编辑器
1. 编辑框太小了
2. 不是所见即所得的 Markdown 编辑器。我并不习惯在没有预览的状态下写 Markdown 语法。尤其篇幅很长，每次编辑后核实修改效果，需要切换预览状态，下拉滚动条到对应修改位置处才能看到效果。

你是怎么对博客再次编辑的，是拷贝出来到本地编辑器编辑，还是就是用 GitHub Issues 自带编辑器？

_Originally posted by @yeshiqing in https://github.com/yihong0618/gitblog/issues/177#issuecomment-1356793407_

**Comment by shyn** [comment]
Sorry for wrong click!

<img width="285" alt="image" src="https://github.com/yihong0618/gitblog/assets/899449/95198a6d-8a63-4bab-bd9c-ef61d1942278">

**Comment by naosense** [comment]
感觉这二点用习惯可以克服吧，特别是第二点，其实md语法那么简单，适应之后，怎么渲染都成竹在胸吧？实时预览的话反而会占用一部分精力，这就和忙打字一样的道理，会陷入不盲打->没有经过大量练习，盲打经常出错->不敢盲打->没有练习的机会的死循环，习惯了就好啦！

**Comment by Nomango** [comment]
我觉得专心写作比呈现效果重要的多，markdown的一大优点就是不需要考虑渲染，只 focus 在文字上，而且 github 编辑器解决了上传图片的路径问题，比在其他编辑器写完，还要整理图片再copy过来舒服很多。

不过 github api 很完善，实现一个三方的 github issue 编辑器完全可以做到，比如 Volta，不过大多数是专门给 issue 管理或者 project 管理做的，编辑体验和 notion typora 什么的还是比不了

**Comment by yihong0618** [comment]
> ```
>           博主你好！我给你写了邮件，担心你收不到，所以在此给你留言。
> ```
> 
> 按你的指导，我也开始用 GitHub Issues 写博客。但是当我「需要再次对博客进行编辑时」感觉体验很不好。 Github Issues 自带的编辑器
> 
> 1. 编辑框太小了
> 2. 不是所见即所得的 Markdown 编辑器。我并不习惯在没有预览的状态下写 Markdown 语法。尤其篇幅很长，每次编辑后核实修改效果，需要切换预览状态，下拉滚动条到对应修改位置处才能看到效果。
> 
> 你是怎么对博客再次编辑的，是拷贝出来到本地编辑器编辑，还是就是用 GitHub Issues 自带编辑器？
> 
> _Originally posted by @yeshiqing in [#177 (comment)](https://github.com/yihong0618/gitblog/issues/177#issuecomment-1356793407)_

我确实没收到邮件。。。

**Comment by shyn** [comment]
哈哈，发现新 issue 也备份了！刚好终于想坚持写博客了，来yihong这里学习，顺便学习github actions。

这个issue编辑器，我试着弄了个全屏的油猴脚本，现学现卖，发现github前端原始的代码都能看到，太方便了！
