### ISSUE TITLE
关于个人博客引入generate_readme.yml文件，实现自由选择博客主题和在issue写文章的问题

### ISSUE THREAD

**Issue by 692** [yihong0618/gitblog#297]
大佬好！我想把generate_readme.yml文件引入我的工作流里面，修改为把md文件写入到Jekyll工具自动发布的`_posts`文件夹里
。这样即可以自由的选择主题模板，又能方便的在issue发布文章。
![image](https://github.com/user-attachments/assets/1326989d-7c25-4198-af9d-53b7d623a536)
但是main.py文件定义的文件名是`dir_name, f"{issue.number}_{issue.title.replace('/', '-').replace(' ', '.')}.md"`，即issue.number+标题，不符合Jekyll工具规定的`yyyy-mm–dd-title.md` 格式。
请教有什么方法可以实现呢？

能否把自动写入的md文件名改为`yyyy-mm–dd-title.md` 这样的格式呢？我自己摸索了一下，把`issue.number`改为`issue.created_at`，文件名在日期后面又多了个时间：

![image](https://github.com/user-attachments/assets/4aba4b5a-4300-4875-b8f2-c5fc9a515391)
还是不符合命名规范。

**Comment by yihong0618** [comment]
你可以改下生成 md 命名的格式，这个问 gpt 就可以成功。
